import competences from "./javascript/competences";
import loader from "./javascript/loader";
import cursor from "./javascript/cursor";
import homeButton from "./javascript/homeButton";
import progressBar from "./javascript/progressBar";
import projets from "./javascript/projets";
import script from "./javascript/script";
import socialMedia from "./javascript/socialMedia";
import apropos from "./javascript/apropos";
import scrollReveal from "./javascript/scrollReveal";

competences();
loader();
cursor();
homeButton();
progressBar();
projets();
script();
socialMedia();
apropos();
scrollReveal();
